pluginManagement {
    def buildConventionPath = System.getenv('BUILD_CONVENTION_PATH')
            ?: '/Users/seongbin/programming/utility/build-convention'

    includeBuild(buildConventionPath)

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'risk-gate'