package io.github.dochiri0916.riskgate.riskassessment.domain.model;

public enum PolicyReason {
    BUILD_CONVENTION_FAILED,
    SEMGREP_CRITICAL,
    RISK_SCORE_BLOCK_THRESHOLD,
    RISK_SCORE_REVIEW_THRESHOLD,
    HIGH_SECURITY_RISK,
    HIGH_AUTHORIZATION_RISK,
    HIGH_DATA_INTEGRITY_RISK,
    HIGH_BREAKING_CHANGE_RISK,
    WITHIN_POLICY_THRESHOLDS
}
